INSERT INTO CARS (CARBRAND, DESCRIPTION, DAILYPRICE) VALUES ('BMW M3','Germany, Munchen motors, petrol', 2500);
INSERT INTO CARS (CARBRAND, DESCRIPTION, DAILYPRICE) VALUES ('Skoda Superb','Made in CZ, diesel', 1500);
INSERT INTO CARS (CARBRAND, DESCRIPTION, DAILYPRICE) VALUES ('Ford Mustang Cobra','Usa distribution, diesel', 4000);
INSERT INTO CARS (CARBRAND, DESCRIPTION, DAILYPRICE) VALUES ('Ferrari 488 Spider','Italy,  max speed > 325 km/h', 2000000);


INSERT INTO CUSTOMERS (FULLNAME, ADDRESS, PHONENUMBER) VALUES ('Jack Black','Minnesota, Avelanche 16', '602463193');
INSERT INTO CUSTOMERS (FULLNAME, ADDRESS, PHONENUMBER) VALUES ('Leonardo di Caprio','New York, Wall Street', '666999333');
INSERT INTO CUSTOMERS (FULLNAME, ADDRESS, PHONENUMBER) VALUES ('God','Heaven', '000');
INSERT INTO CUSTOMERS (FULLNAME, ADDRESS, PHONENUMBER) VALUES ('Gal Gadot','Los Angeles 1514 N Gower St, California', '723659708');

INSERT INTO LEASES (LEASEDCARID, CUSTOMERID, STARTDATE, ENDDATE, PRICE) VALUES (1,1, '2017-11-19', '2018-01-03', 25000);
INSERT INTO LEASES (LEASEDCARID, CUSTOMERID, STARTDATE, ENDDATE, PRICE) VALUES (4,4, '2018-05-15', '2018-06-15', 30000);

